### ISSUE TITLE
Even the version command does not work with the current version

### ISSUE THREAD

**Issue by takehaya** [erkanzileli/co-author#2]
# Why
```shell
$ co-author version         
commit msg file does not specified on args, please check your git hook
$ co-author --help          
commit msg file does not specified on args, please check your git hook
```

It's not working properly. It seems to be deviating from the state of the document written in README. Please teach me how to use it 🙏

**Comment by erkanzileli** [comment]
You're absolutely right. Let me fix that stupid mistake. Sorry for breaking your experience 😢

**Comment by takehaya** [comment]
Thank you for responding!(and Thanks for the great fix!

It's a nits story, but it would be even better if the README was also updated!：) (e.g. `.git-co-authors.yaml`-> `.co-author.yaml`
https://github.com/erkanzileli/co-author#load-config
